### ISSUE TITLE
CoreApiSpec > should fail for not balanced flow FAILED

### ISSUE THREAD

**Issue by szpak** [piotrpietrzak/aprcalc#1]
Wrong exception is thrown in master. It seems to work on Travis. Tested with OpenJDK 1.8.0_77 and Oracle JDK 1.8.0_51.

```
me.pietrzak.aprcalc.CoreApiSpec > should fail for not balanced flow FAILED
    org.spockframework.runtime.WrongExceptionThrownError at CoreApiSpec.groovy:36
        Caused by: java.lang.ArithmeticException at CoreApiSpec.groovy:34

37 tests completed, 1 failed
:test FAILED
```

```
Expected exception of type 'java.lang.UnsupportedOperationException', but got 'java.lang.ArithmeticException'
    at org.spockframework.lang.SpecInternals.checkExceptionThrown(SpecInternals.java:79)
    at org.spockframework.lang.SpecInternals.thrownImpl(SpecInternals.java:66)
    at me.pietrzak.aprcalc.CoreApiSpec.should fail for not balanced flow(CoreApiSpec.groovy:36)
Caused by: java.lang.ArithmeticException: BigInteger divide by zero
    at java.math.MutableBigInteger.divide(MutableBigInteger.java:1440)
    at java.math.BigDecimal.divideAndRound(BigDecimal.java:4248)
    at java.math.BigDecimal.divide(BigDecimal.java:5161)
    at java.math.BigDecimal.divide(BigDecimal.java:1561)
    at me.pietrzak.aprcalc.root.NewtonsMethod.findZero(NewtonsMethod.java:30)
    at me.pietrzak.aprcalc.APRCalc.calculate(APRCalc.java:27)
    at me.pietrzak.aprcalc.CoreApiSpec.should fail for not balanced flow(CoreApiSpec.groovy:34)
```

**Comment by piotrpietrzak** [comment]
http://www.pietrzak.me/2016/04/shadows-of-bigdecimal.html
Equals has not the same meaning as equal in terms of compareTo method.
